name: Update JSON from Google Sheets

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecutar todos los días a la medianoche
  workflow_dispatch:    # Permite ejecución manual

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch JSON from Google Drive
        run: |
          curl -L "https://drive.google.com/uc?export=download&id=1EDuhf-T6rob5vbprXxEmZSOC_Lu_Ff9y" -o JS/JsonTest.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add JS/JsonTest.json
          git commit -m "Update JSON from Google Sheets"
          git push
